### ISSUE TITLE
performance results 

### ISSUE THREAD

**Issue by jinz2014** [hipdac-lab/GPULZ#1]
could you please explain the  performance results ? Thanks.

nvcc gpulz.cu -arch sm_80 -o gpulz

On an A100 GPU
./gpulz -i ./tpch/tpch@0.2-00.bin
compression ratio: 1.89036
compression e2e throughput: 10.1596 GB/s
decompression e2e throughput: 11.0376 GB/s

Your results:
compression ratio: 11.5429
compression e2e throughput: 20.9908 GB/s
decompression e2e throughput: 34.4679 GB/s

**Comment by boyuanzhang62** [comment]
Hello, thanks for letting us know. I've tested the case you mentioned and you are right. I put the result log of another file on the readme. You can try this file, which is the corresponding one for this performance result, QCLOUDf48.bin.f32.errctrl.1e-3. To download it you can uncomment the "wget --quiet https://cgi.luddy.indiana.edu/~ditao/data/02_HURR_zyx_100x500x500=25000000.zip" in the get_sample_data.sh. Thanks again for pointing out. We apologize for the inconvenience. I've also updated the readme.md.
